# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
csv_path = "../WeatherPy/output_data/cities.csv"
df = pd.read_csv(csv_path)
df.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,kattivakkam,40,IN,1584484038,83,13.22,80.32,82.00,2.24
1,jijiga,1,ET,1584484038,71,9.35,42.80,67.37,5.01
2,ushuaia,40,AR,1584484038,44,-54.80,-68.30,57.20,17.22
3,sines,100,PT,1584484039,66,37.96,-8.87,54.00,3.00
4,karasjok,75,NO,1584484039,85,69.47,25.51,24.80,2.24

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# see api day 3 exercise 10
gmaps.configure(api_key=g_key)
locations = df[["Lat", "Lng"]].astype(float)
humidity = df["Humidity"].astype(float)

In [4]:
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
ideal_df = df.loc[(df["Max Temp"] > 78) & (df["Max Temp"] < 90) & (df["Wind Speed"] < 9) & (df["Cloudiness"] == 0)]
ideal_df = ideal_df.dropna()

ideal_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
9,linares,0,CL,1584484039,13,-35.85,-71.60,83.93,6.04
14,buala,0,SB,1584484040,81,-8.14,159.59,80.69,2.21
80,dwarka,0,IN,1584484048,58,22.24,68.97,78.53,8.23
119,san patricio,0,MX,1584483803,74,19.22,-104.70,78.17,7.11
226,kavaratti,0,IN,1584484068,67,10.57,72.64,82.85,7.34
276,roura,0,GF,1584484075,78,4.73,-52.33,80.60,4.70
289,keita,0,NE,1584484076,7,14.76,5.77,87.80,2.24
399,auki,0,SB,1584484100,74,-8.77,160.70,83.75,3.76
464,kieta,0,PG,1584484109,79,-6.22,155.63,80.33,4.05

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
# see api day 3 exercise 4
hotel_df = ideal_df.copy()
hotel_df["Hotel Name"] = ""

In [12]:
import json

target_radius = 5000

params = {
    "location": "39.952583,-75.16522",  # philadelphia coords,
    "radius": target_radius,
    "type": "lodging",
    "key": g_key,
}

# will loop through df, adding lat and long as "location" parameter before making the request and adding to df


base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# for index, row in hotel_df.iterrows():
#     location = f'{row["Lng"]},{row["Lat"]}'
#     params["location"] = location
#     response = requests.get(base_url, params=params)
#     results = response['results']
# #     all_results.append(results)
# #     print(location)
#     print(results)
#     print(response.url)
    
response = requests.get(base_url, params=params)
# print(response.url)

In [ ]:
# TODO - modify this - whether it produces results or not, using 5000, and logding, get marker layer set up.  Format and clean, submit

# params dictionary to update each iteration
params = {
    "radius": 50000,
    "types": "airport",
    "keyword": "international airport",
    "key": gkey
}

# Use the lat/lng we recovered to identify airports
for index, row in cities_pd.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "International Airport" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)
    
#     print the name_address url, avoid doing for public github repos in order to avoid exposing key
#     print(name_address.url)

    # convert to json
    name_address = name_address.json()
    # print(json.dumps(name_address, indent=4, sort_keys=True))

    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        cities_pd.loc[index, "Airport Name"] = name_address["results"][0]["name"]
#         cities_pd.loc[index, "Airport Address"] = name_address["results"][0]["vicinity"]
#         cities_pd.loc[index, "Airport Rating"] = name_address["results"][0]["rating"]
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in ideal_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map

markers = gmaps.marker_layer(locations)
fig.add_layer(markers)

# Display Map

fig